"""Initial database creation

Revision ID: 4d08f464861e
Revises: 
Create Date: 2025-03-09 09:52:56.432343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d08f464861e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('mac_address')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=17), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.mac_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=17), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('env_humidity', sa.Float(), nullable=True),
    sa.Column('env_temperature', sa.Float(), nullable=True),
    sa.Column('ground_sensor_1', sa.Float(), nullable=True),
    sa.Column('ground_sensor_2', sa.Float(), nullable=True),
    sa.Column('ground_sensor_3', sa.Float(), nullable=True),
    sa.Column('ground_sensor_4', sa.Float(), nullable=True),
    sa.Column('ground_sensor_5', sa.Float(), nullable=True),
    sa.Column('ground_sensor_6', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.mac_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_activities_device_id'), 'sensor_activities', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_activities_device_id'), table_name='sensor_activities')
    op.drop_table('sensor_activities')
    op.drop_table('notifications')
    op.drop_table('devices')
    # ### end Alembic commands ###
