services:
  postgres:
    image: postgres:15
    container_name: agro_sensor_hub_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - agro_sensor_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: agro_sensor_hub_backend
    environment:
      - PORT=${PORT}
      - API_PREFIX=${API_PREFIX}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - agro_sensor_network

networks:
  agro_sensor_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 